// frontend/src/app/components/edit-assembly-form/edit-assembly-form.component.ts
import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { ApiClientService } from '../../services/api-client.service';

@Component({
  selector: 'app-edit-assembly-form',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './edit-assembly-form.component.html',
  styleUrls: ['./edit-assembly-form.component.css'],
})
export class EditAssemblyFormComponent implements OnInit {
  @Input() assembly: any; // Recibe el ensamblaje a editar
  @Output() onCancel = new EventEmitter<void>(); // Evento para cancelar la edición
  @Output() onSave = new EventEmitter<void>(); // Evento para guardar los cambios
  editForm!: FormGroup;
  suppliers: any[] = [];

  constructor(private fb: FormBuilder, private apiClient: ApiClientService) {}

  ngOnInit(): void {
    // Cargar lista de suppliers
    this.apiClient.getSuppliers().subscribe({
      next: (data) => {
        this.suppliers = data;
      },
      error: (err) => console.error('Error loading suppliers:', err),
    });
    

    // Inicializa el formulario con los datos del ensamblaje
    this.editForm = this.fb.group({
      assembly_name: [this.assembly?.assembly_name || '', Validators.required],
      part_number: [this.assembly?.part_number || '', Validators.required],
      indice: [this.assembly?.indice || '', Validators.required],
      version: [this.assembly?.version || '', Validators.required],
      eng_type: [this.assembly?.eng_type || 1, Validators.required],
      supplier: [this.assembly?.supplier?.supplier_name || '', Validators.required],
    });    
  }

  saveChanges(): void {
    if (this.editForm.valid) {
      const updatedAssembly = {
        ...this.assembly,
        ...this.editForm.value, // Incluye el ID del supplier
      };
  
      console.log('Datos enviados al backend:', updatedAssembly); // Verifica los datos actualizados
  
      this.apiClient.put(`${this.assembly.id}`, updatedAssembly).subscribe({
        next: () => {
          console.log('Assembly updated successfully');
          this.onSave.emit(); // Emitir evento al guardar
        },
        error: (err) => {
          console.error('Error updating assembly:', err);
        },
      });
    } else {
      console.warn('Formulario inválido');
    }
  }
  

  cancel(): void {
    this.onCancel.emit(); // Emite el evento al cancelar
  }
}

<div class="card mb-4">
    <div class="card-header">Edit Assembly</div>
    <div class="card-body">
      <form [formGroup]="editForm" (ngSubmit)="saveChanges()">
        <div class="mb-3">
          <label for="assembly_name" class="form-label">Assembly Name</label>
          <input
            type="text"
            id="assembly_name"
            formControlName="assembly_name"
            class="form-control"
          />
        </div>
        <div class="mb-3">
          <label for="part_number" class="form-label">Part Number</label>
          <input
            type="text"
            id="part_number"
            formControlName="part_number"
            class="form-control"
          />
        </div>
        <div class="mb-3">
          <label for="indice" class="form-label">Index</label>
          <input
            type="text"
            id="indice"
            formControlName="indice"
            class="form-control"
          />
        </div>
        <div class="mb-3">
          <label for="version" class="form-label">Version</label>
          <input
            type="number"
            id="version"
            formControlName="version"
            class="form-control"
          />
        </div>
        <div class="mb-3">
          <label for="eng_type" class="form-label">Eng Type</label>
          <select
            id="eng_type"
            formControlName="eng_type"
            class="form-select"
          >
            <option value="1">SET</option>
            <option value="2">ASSY</option>
          </select>
        </div>
        <div class="mb-3">
          <label for="supplier" class="form-label">Supplier</label>
          <select id="supplier" formControlName="supplier" class="form-select">
            <option *ngFor="let supplier of suppliers" [value]="supplier.supplier_name">
              {{ supplier.supplier_name }}
            </option>
          </select>          
        </div>        
        <button type="submit" class="btn btn-primary">Save</button>
        <button type="button" class="btn btn-secondary ms-2" (click)="cancel()">Cancel</button>
      </form>
    </div>
  </div>

// frontend_1/src/components/EditAssemblyForm.jsx
import React, { useState } from 'react';
import apiClient from '../api';

const EditAssemblyForm = ({ assembly, onCancel, onSave }) => {
    const [formData, setFormData] = useState({
        assembly_name: assembly.assembly_name || '',
        part_number: assembly.part_number || '',
        indice: assembly.indice || '',
        version: assembly.version || '',
        eng_type: assembly.eng_type || '1', // Valor predeterminado "SET" (1)
      });
      

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    const url = `/poeassy/assembly/${assembly.id}`;
  
    try {
      const response = await apiClient.put(url, formData);
      console.log('Update successful:', response.data);
      onSave();
    } catch (error) {
      console.error('Error updating assembly:', error.response || error.message);
    }
  };
  

  return (
    <div className="card mb-4">
      <div className="card-header">Edit Assembly</div>
      <div className="card-body">
        <form onSubmit={handleSubmit}>
          <div className="mb-3">
            <label htmlFor="assembly_name" className="form-label">Assembly Name</label>
            <input
              type="text"
              className="form-control"
              id="assembly_name"
              name="assembly_name"
              value={formData.assembly_name}
              onChange={handleChange}
            />
          </div>
          <div className="mb-3">
            <label htmlFor="part_number" className="form-label">Part Number</label>
            <input
              type="text"
              className="form-control"
              id="part_number"
              name="part_number"
              value={formData.part_number}
              onChange={handleChange}
            />
          </div>
          <div className="mb-3">
            <label htmlFor="indice" className="form-label">Indice</label>
            <input
              type="text"
              className="form-control"
              id="indice"
              name="indice"
              value={formData.indice}
              onChange={handleChange}
            />
          </div>
          <div className="mb-3">
            <label htmlFor="version" className="form-label">Version</label>
            <input
              type="number"
              className="form-control"
              id="version"
              name="version"
              value={formData.version}
              onChange={handleChange}
            />
          </div>
          <div className="mb-3">
            <label htmlFor="eng_type" className="form-label">Eng Type</label>
            <select
                className="form-select"
                id="eng_type"
                name="eng_type"
                value={formData.eng_type}
                onChange={handleChange}
            >
                <option value="1">SET</option>
                <option value="2">ASSY</option>
            </select>
          </div>
          <button type="submit" className="btn btn-primary">Save</button>
          <button type="button" className="btn btn-secondary ms-2" onClick={onCancel}>Cancel</button>
        </form>
      </div>
    </div>
  );
  
};

export default EditAssemblyForm;
